### ISSUE TITLE
A simpler way to append to a path

### ISSUE THREAD

**Issue by calpaterson** [zacharyvoase/urlobject#37]
In urlobject I think the best way to add to an existing path is:

```
from urlobject import URLObject
url = URLObject("http://example.com/prefix-to-api-paths/"
segments = ["api", "demo"]
for segment in segments:
    url = url.with_path(url.path.add_segment(segment))
```

Other options, like using `with_path`, `add_path` or `add_path_segment` will remove the existing path.  Is there any scope to add a new method for this usecase?

**Comment by agriffis** [comment]
`add_path` and `add_path_segment` only remove the existing path if there's a leading slash.

```
In [1]: from urlobject import URLObject

In [2]: URLObject('http://example.com/prefix-to-api-paths/').add_path('foo/bar')
Out[2]: URLObject(u'http://example.com/prefix-to-api-paths/foo/bar')

In [3]: URLObject('http://example.com/prefix-to-api-paths/').add_path('/foo/bar')
Out[3]: URLObject(u'http://example.com/foo/bar')

In [8]: URLObject('http://example.com/prefix-to-api-paths/').add_path('foo/bar/')
Out[8]: URLObject(u'http://example.com/prefix-to-api-paths/foo/bar/')
```

Does this solve the problem for you?

**Comment by agriffis** [comment]
Also the existing prefix doesn't need to end in slash for it to work:

```
In [2]: URLObject('http://example.com/prefix-to-api-paths').add_path('foo/bar')
Out[2]: URLObject(u'http://example.com/prefix-to-api-paths/foo/bar')
```

**Comment by calpaterson** [comment]
Ah, I didn't know that.  That does solve my problem.  Perhaps that could be added to the docstring for those two methods?

**Comment by agriffis** [comment]
@calpaterson Please feel free to submit a PR updating docstrings, if you don't mind that it might not get into a release for a while.
